apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pi-server-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: pi-server
    spec:
      containers:
        - name: pi-server
          image: memes/pi:1.0.0
          command: [ "/usr/local/bin/pi", "server", "--verbose" ]
          ports:
            - containerPort: 8080
              name: alt-http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pi-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: alt-http
  selector:
    app: pi-server
