apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        class: redis
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: class
                      operator: In
                      values:
                        - redis
                    - key: app
                      operator: In
                      values:
                        - redis
                topologyKey: kubernetes.io/hostname
      containers:
        - name: bootstrap
          image: memes/redis:1.0.1
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 45
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    class: redis
spec:
  ports:
    - port: 6379
      targetPort: redis
  selector:
    app: redis
    class: redis
